const UPDATE_BOREDLE_MODE = 'UPDATE_BOREDLE_MODE'

const GET_WOTD_SUCCESS = 'GET_WOTD_SUCCESS'
const GET_WOTD_ERROR = 'GET_WOTD_ERROR'

export { UPDATE_BOREDLE_MODE, GET_WOTD_SUCCESS, GET_WOTD_ERROR }
