export const OPTION_COMBO_ERROR = 'OPTION_COMBO_ERROR'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const RETRIEVE_CATEGORIES = 'RETRIEVE_CATEGORIES'

export const UPDATE_GAME_OPTIONS = 'UPDATE_GAME_OPTIONS'

export const LOAD_QUESTIONS_BEGIN = 'LOAD_QUESTIONS_BEGIN'
export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS'
export const LOAD_QUESTIONS_ERROR = 'LOAD_QUESTIONS_ERROR'

export const START_GAME = 'START_GAME'
