export const UPDATE_BOREDLE_MODE = 'UPDATE_BOREDLE_MODE'

export const TOGGLE_HELP_MODAL = 'TOGGLE_HELP_MODAL'
export const TOGGLE_SETTINGS_MODAL = 'TOGGLE_SETTINGS_MODAL'

export const GET_WOTD_SUCCESS = 'GET_WOTD_SUCCESS'
export const GET_WOTD_ERROR = 'GET_WOTD_ERROR'
