export const UPDATE_BOREDLE_MODE = 'UPDATE_BOREDLE_MODE'

export const TOGGLE_HARD_MODE = 'TOGGLE_HARD_MODE'
export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE'
export const TOGGLE_HIGH_CONTRAST_MODE = 'TOGGLE_HIGH_CONTRAST_MODE'

export const TOGGLE_HELP_MODAL = 'TOGGLE_HELP_MODAL'
export const TOGGLE_SETTINGS_MODAL = 'TOGGLE_SETTINGS_MODAL'

export const SHOW_ALERT_MODAL = 'SHOW_ALERT_MODAL'
export const HIDE_ALERT_MODAL = 'HIDE_ALERT_MODAL'

export const INVALID_GUESS_START = 'INVALID_GUESS_START'
export const INVALID_GUESS_STOP = 'INVALID_GUESS_STOP'

export const IS_REVEALING_START = 'IS_REVEALING_START'
export const IS_REVEALING_STOP = 'IS_REVEALING_STOP'

export const GET_MY_BOREDLE_SUCCESS = 'GET_MY_BOREDLE_SUCCESS'
export const GET_MY_BOREDLE_ERROR = 'GET_MY_BOREDLE_ERROR'

export const HANDLE_KEYBOARD_LETTER = 'HANDLE_KEYBOARD_LETTER'
export const HANDLE_KEYBOARD_BACKSPACE = 'HANDLE_KEYBOARD_BACKSPACE'

export const SUBMIT_GOTD_GUESS = 'SUBMIT_GOTD_GUESS'
export const SUBMIT_PRACTICE_GUESS = 'SUBMIT_PRACTICE_GUESS'

export const HANDLE_WIN = 'HANDLE_WIN'
export const HANDLE_LOSS = 'HANDLE_LOSS'

