export const UPDATE_BOREDLE_MODE = 'UPDATE_BOREDLE_MODE'

export const TOGGLE_HARD_MODE = 'TOGGLE_HARD_MODE'
export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE'
export const TOGGLE_HIGH_CONTRAST_MODE = 'TOGGLE_HIGH_CONTRAST_MODE'

export const TOGGLE_HELP_MODAL = 'TOGGLE_HELP_MODAL'
export const TOGGLE_SETTINGS_MODAL = 'TOGGLE_SETTINGS_MODAL'

export const GET_WOTD_SUCCESS = 'GET_WOTD_SUCCESS'
export const GET_WOTD_ERROR = 'GET_WOTD_ERROR'

export const HANDLE_KEYBOARD_LETTER = 'HANDLE_KEYBOARD_LETTER'
export const HANDLE_KEYBOARD_BACKSPACE = 'HANDLE_KEYBOARD_BACKSPACE'
export const HANDLE_KEYBOARD_ENTER = 'HANDLE_KEYBOARD_ENTER'
