export const MISSING_FIELDS_ALERT = 'MISSING_FIELDS_ALERT'
export const OPTION_COMBO_ERROR = 'OPTION_COMBO_ERROR'
export const CLEAR_ALERT = 'CLEAR_ALERT'
export const DISPLAY_ALERT = 'DISPLAY_ALERT'

export const RETRIEVE_PRACTICE_CATEGORIES = 'RETRIEVE_PRACTICE_CATEGORIES'

export const UPDATE_PRACTICE_OPTIONS = 'UPDATE_PRACTICE_OPTIONS'

export const LOAD_PRACTICE_BEGIN = 'LOAD_PRACTICE_BEGIN'
export const LOAD_PRACTICE_SUCCESS = 'LOAD_PRACTICE_SUCCESS'
export const LOAD_PRACTICE_ERROR = 'LOAD_PRACTICE_ERROR'

export const START_PRACTICE = 'START_PRACTICE'
export const RESET_PRACTICE_OPTIONS = 'RESET_PRACTICE_OPTIONS'

export const SELECT_PRACTICE_ANSWER = 'SELECT_PRACTICE_ANSWER'

export const TOGGLE_PRACTICE_QUESTION = 'TOGGLE_PRACTICE_QUESTION'

export const SUBMIT_PRACTICE_ANSWERS = 'SUBMIT_PRACTICE_ANSWERS'

export const CHANGE_THEME = 'CHANGE_THEME'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const UPDATE_PASSWORD_BEGIN = 'UPDATE_PASSWORD_BEGIN'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_ERROR = 'UPDATE_PASSWORD_ERROR'
