export const MISSING_FIELDS_ALERT = 'MISSING_FIELDS_ALERT'
export const OPTION_COMBO_ERROR = 'OPTION_COMBO_ERROR'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const RETRIEVE_CATEGORIES = 'RETRIEVE_CATEGORIES'

export const UPDATE_GAME_OPTIONS = 'UPDATE_GAME_OPTIONS'

export const LOAD_QUESTIONS_BEGIN = 'LOAD_QUESTIONS_BEGIN'
export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS'
export const LOAD_QUESTIONS_ERROR = 'LOAD_QUESTIONS_ERROR'

export const START_GAME = 'START_GAME'
export const RESET_OPTIONS = 'RESET_OPTIONS'

export const SELECT_ANSWER = 'SELECT_ANSWER'

export const TOGGLE_QUESTION = 'TOGGLE_QUESTION'

export const SUBMIT_ANSWERS = 'SUBMIT_ANSWERS'

export const CHANGE_THEME = 'CHANGE_THEME'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'
